version: "3.8"

volumes:
  postgres_data:
      driver: local
  prometheus_data: {}

services:

  postgres:
    container_name: POSTGRES
    image: postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  keycloak:
    container_name: KEYCLOAK
    image: jboss/keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      PROXY_ADDRESS_FORWARDING: "true"
    ports:
      - 9990:8080
      - 9991:8443
    depends_on:
      - postgres

  redis:
    container_name: REDIS
    image: redis
    ports:
      - 6379:6379

  rabbitmq:
    container_name: RABBITMQ
    image: bitnami/rabbitmq
    environment:
      - RABBITMQ_PLUGINS=rabbitmq_management,rabbitmq_stomp,rabbitmq_web_stomp,rabbitmq_stream,rabbitmq_top
    ports:
      - 5672:5672
      - 15672:15672
      - 61613:61613
    networks:
      - rabbitmq_go_net

  prometheus:
    container_name: PROMETHEUS
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes: 
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'  

  grafana:
    container_name: GRAFANA
    image: grafana/grafana
    links: 
      - prometheus
    ports:
      - 3001:3000

networks:
  rabbitmq_go_net:
    driver: bridge