server:
  port: 8888

keycloak:
  realm: chat-app-realm
  bearer-only: true
  auth-server-url: http://localhost:9990/auth
  resource: chat-app-client
  ssl-required: external


spring:
  main:
    allow-circular-references: true
  application:
    name: SOCKET-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
