server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/user/**
        - id: DIRECT-MESSAGE-SERVICE
          uri: lb://DIRECT-MESSAGE-SERVICE
          predicates:
            - Path=/api/v1/direct_message/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service_url:
      defaultZone: http://localhost:8761/eureka/
  instance: localhost