server:
  port: 9191

spring:
  application:
    name: API-GATEWAY #name of the app for eureka server

  redis:
    host: localhost
    port: 6379 #redis port

  cloud:
    gateway:

      default-filters:
        - name: RequestRateLimiter #redis rate limiter
          args:
            redis-rate-limiter.replenishRate: 50
            redis-rate-limiter.burstCapacity: 250
            redis-rate-limiter.requestedTokens: 25

      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/user/**
          filters:
            - name: CircuitBreaker
              args:
                name: userService
                fallbackUri: forward:/userServiceFallback

        - id: MESSAGE-SERVICE
          uri: lb://MESSAGE-SERVICE
          predicates:
            - Path=/api/v1/message/**
          filters:
            - name: CircuitBreaker
              args:
                name: messageService
                fallbackUri: forward:/messageServiceFallback

        - id: CHANNEL-SERVICE
          uri: lb://CHANNEL-SERVICE
          predicates:
            - Path=/api/v1/channel/**
          filters:
            - name: CircuitBreaker
              args:
                name: channelService
                fallbackUri: forward:/channelServiceFallback

resilience4j:
  circuitbreaker:
    instances:

      userService:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15000
        registerHealthIndicator: true

      messageService:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15000
        registerHealthIndicator: true

      channelService:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15000
        registerHealthIndicator: true

  timelimiter:
    instances:
      userService:
        timeoutDuration: 2s
      messageService:
        timeoutDuration: 2s
      channelService:
        timeoutDuration: 2s

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service_url:
      defaultZone: http://localhost:8761/eureka/
  instance: localhost