server:
  port: 9191

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            auth-server-url: http://192.168.0.103:9990/auth
            realm: chat-app-realm
            issuer-uri: http://192.168.0.103:9990/auth/realms/chat-app-realm
        registration:
          keycloak-gateway:
            provider: keycloak
            client-id: chat-app-client
            client-secret: c22a1d71-df57-4ab2-9998-6d96239d4453
            client-name: chatapp
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
  application:
    name: API-GATEWAY #name of the app for eureka server

  redis:
    host: localhost
    port: 6379 #redis port
    connect-timeout: 30s
    timeout: 500ms
  session:
    store-type: redis
    timeout: 10m
    redis:
      namespace: chatapp:gateway

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            
      default-filters:
        - SaveSession
        - TokenRelay
        - name: RequestRateLimiter #redis rate limiter
          args:
            redis-rate-limiter.replenishRate: 50
            redis-rate-limiter.burstCapacity: 250
            redis-rate-limiter.requestedTokens: 25

      routes:

        - id: MESSAGE-SERVICE
          uri: lb://MESSAGE-SERVICE
          predicates:
            - Path=/api/v1/message/**
          filters:
            - name: CircuitBreaker
              args:
                name: messageService
                fallbackUri: forward:/messageServiceFallback

        - id: SOCKET-SERVICE
          uri: lb://SOCKET-SERVICE
          predicates:
            - Path=/api/v1/socket/**
          filters:
            - name: CircuitBreaker
              args:
                name: socketService
                fallbackUri: forward:/socketServiceFallback


resilience4j:
  circuitbreaker:
    instances:

      messageService:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15000
        registerHealthIndicator: true

      socketService:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15000
        registerHealthIndicator: true


  timelimiter:
    instances:

      messageService:
        timeoutDuration: 2s

      socketService:
        timeoutDuration: 2s


management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service_url:
      defaultZone: http://localhost:8761/eureka/
  instance: localhost